messenger4j:
  appSecret: ${MESSENGER_APP_SECRET}
  verifyToken: ${MESSENGER_VERIFY_TOKEN}
  pageAccessToken: ${MESSENGER_PAGE_ACCESS_TOKEN}

logging:
  level:
    ROOT: INFO
    com.github.messenger4j: INFO
    tk.germanbot: INFO?

aws:
  dynamodb:
    endpoint: http://localhost:8000/
    accessKey: 123 #${AWS_ACCESS_KEY_ID}
    secretKey: 456 #${AWS_SECRET_ACCESS_KEY}