messenger4j:
  appSecret: ${MESSENGER_APP_SECRET}
  verifyToken: ${MESSENGER_VERIFY_TOKEN}
  pageAccessToken: ${MESSENGER_PAGE_ACCESS_TOKEN}

logging:
  level:
    ROOT: INFO
    com.github.messenger4j: INFO
    tk.germanbot: INFO?

aws:
  dynamodb:
    region: eu-central-1
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    readThroughput: 10
    writeThroughput: 5

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

aws:
  dynamodb:
    endpoint: http://localhost:8000/
    accessKey: testkey
    secretKey: testsecret
